### ISSUE TITLE
Section in yml config file is not being detected in scanned files

### ISSUE THREAD

**Issue by alexlance** [shoukoo/tf-verifier#10]
Given this yaml:

```
aws_s3_bucket:
  tags:
    - Name
    - function
    - product
    - terraform
    - service
  logging:
    - target_bucket
    - target_prefix
  server_side_encryption_configuration:
```

And running tfv over this file:
```
resource "aws_s3_bucket" "redacted" {
  bucket = "redacted"
  logging {
    target_bucket = "refacted"
    target_prefix = "redacted/"
  }
}
```

tfv prints a warning about missing the logging section. I'd expect that the logging section would be found. tfv version:

```
$ tfv --version
FATA[0000] Can't find config file open tf.yaml: no such file or directory 
```

**Comment by shoukoo** [comment]
TFV wasn't handling hcl.TraverseAttr type, I have pushed a fix to this PR- https://github.com/shoukoo/tfv/pull/11

```
ERRO[0000] Unknown traverser type hcl.TraverseAttr
ERRO[0000] Unknown trarverser type hcl.TraverseAttr
````

**Comment by alexlance** [comment]
This is still a problem even in 0.0.3. 
```
aws_s3_bucket:
  tags:
    - Name
    - function
    - product
    - terraform
    - service
  logging:
    - target_bucket
    - target_prefix
  server_side_encryption_configuration:
+    rule:
+      apply_server_side_encryption_by_default:


aws_instance:
  tags:
    - Name
    - function
    - product
    - terraform
- service
```
The two lines I've added above (prefixed with +) cause it to error out with this:

```
FATA[0000] error preparing task yaml: unmarshal errors:
line 12: cannot unmarshal !!map into []string
```

**Comment by shoukoo** [comment]
Added a fix to this PR - https://github.com/shoukoo/tfv/pull/12

In order for the above to work, you need to use the following format

```
server_side_encryption_configuration:
  - rule
  - apply_server_side_encryption_by_default
  - kms_master_key_id
  - sse_algorithm
```

**Comment by shoukoo** [comment]
I had second thoughts and write another fix for the above issue in this PR https://github.com/shoukoo/tfv/pull/12

```
aws_instance:
  tags:
    - Name
    - terraform

  lifecycle:
    - create_before_destroy

aws_s3_bucket:
  logging:
    - target_bucket
    - target_prefix

  server_side_encryption_configuration:
    - rule:
      - apply_server_side_encryption_by_default:
        - kms_master_key_id
        - sse_algorithm
```

**Comment by shoukoo** [comment]
Fixed
